
blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/ardalis/GuardClauses/discussions/categories/q-a
    about: Please ask and answer questions in the Discussions Q&A tab.
    
